// Code generated by sdp-gen. DO NOT EDIT.

use super::types::*;
use sdp::wire::{Decoder, Result};
use std::io::Read;

impl Device {
    pub fn decode<R: Read>(reader: &mut R) -> Result<Self> {
        let mut dec = Decoder::new(reader);
        let id = dec.read_u32()?;
        let name = dec.read_string()?;
        Ok(Self {
            id,
            name,
        })
    }
}

