// Code generated by sdp-gen. DO NOT EDIT.

use super::types::*;
use sdp::wire::{Encoder, Result};
use std::io::Write;

impl Device {
    pub fn encode<W: Write>(&self, writer: &mut W) -> Result<()> {
        let mut enc = Encoder::new(writer);
        enc.write_u32(self.id)?;
        enc.write_string(&self.name)?;
        Ok(())
    }
}

