/* encode.hpp - Encoding functions for messagemode
 * Generated by sdp-gen - DO NOT EDIT
 */

#ifndef MESSAGEMODE_ENCODE_HPP
#define MESSAGEMODE_ENCODE_HPP

#include "types.hpp"
#include <cstdint>
#include <cstddef>

namespace sdp {

/* Calculate encoded size of Point */
size_t point_size(const Point& msg);

/* Encode Point to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least point_size() bytes
 */
size_t point_encode(const Point& msg, uint8_t* buf);

/* Calculate encoded size of Rectangle */
size_t rectangle_size(const Rectangle& msg);

/* Encode Rectangle to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least rectangle_size() bytes
 */
size_t rectangle_encode(const Rectangle& msg, uint8_t* buf);

}  // namespace sdp

#endif  // MESSAGEMODE_ENCODE_HPP
