/* types.hpp - Type definitions for messagemode
 * Generated by sdp-gen - DO NOT EDIT
 * 
 * C++17 type definitions using:
 * - std::string for strings (null-terminated, length tracked)
 * - std::vector<T> for arrays (size tracked automatically)
 * - std::optional<T> for optional fields (type-safe)
 * 
 * Zero runtime dependencies, RAII memory management.
 */

#ifndef MESSAGEMODE_TYPES_HPP
#define MESSAGEMODE_TYPES_HPP

#include <cstdint>
#include <string>
#include <vector>
#include <optional>

namespace sdp {

/* Point */
struct Point {
    // x
    double x;
    // y
    double y;
};

/* Rectangle */
struct Rectangle {
    // top_left
    Point top_left;
    // width
    double width;
    // height
    double height;
};

}  // namespace sdp

#endif  // MESSAGEMODE_TYPES_HPP
