// Code generated by sdp-gen. DO NOT EDIT.

use super::types::*;
use sdp::wire::{Decoder, Result};
use std::io::Read;

impl Example {
    pub fn decode<R: Read>(reader: &mut R) -> Result<Self> {
        let mut dec = Decoder::new(reader);
        let field = dec.read_u32()?;
        Ok(Self {
            field,
        })
    }
}

