// swift-tools-version:5.9
// Code generated by sdp-gen. DO NOT EDIT.
import PackageDescription

let package = Package(
    name: "optional",
    platforms: [
        .macOS(.v10_15),
        .iOS(.v13),
        .watchOS(.v6),
        .tvOS(.v13)
    ],
    products: [
        .library(
            name: "optional",
            targets: ["optional"]),
    ],
    targets: [
        .target(
            name: "optional",
            dependencies: [],
            cxxSettings: [
                .unsafeFlags(["-std=c++17"]),
            ],
            swiftSettings: [
                // Enable C++ interop (Swift 5.9+)
                .interoperabilityMode(.Cxx),
                // Optimization flags
                .unsafeFlags(["-O", "-whole-module-optimization"]),
            ]),
    ]
)
