/* encode.hpp - Encoding functions for primitives_cpp
 * Generated by sdp-gen - DO NOT EDIT
 */

#ifndef PRIMITIVES_CPP_ENCODE_HPP
#define PRIMITIVES_CPP_ENCODE_HPP

#include "types.hpp"
#include <cstdint>
#include <cstddef>

namespace sdp {

/* Calculate encoded size of AllPrimitives */
size_t all_primitives_size(const AllPrimitives& msg);

/* Encode AllPrimitives to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least all_primitives_size() bytes
 */
size_t all_primitives_encode(const AllPrimitives& msg, uint8_t* buf);

}  // namespace sdp

#endif  // PRIMITIVES_CPP_ENCODE_HPP
