// Generated by sdp-gen - DO NOT EDIT

import Foundation

public struct AllPrimitives {
    public var u8Field: UInt8
    public var u16Field: UInt16
    public var u32Field: UInt32
    public var u64Field: UInt64
    public var i8Field: Int8
    public var i16Field: Int16
    public var i32Field: Int32
    public var i64Field: Int64
    public var f32Field: Float
    public var f64Field: Double
    public var boolField: Bool
    public var strField: String
}
