// Code generated by sdp-gen. DO NOT EDIT.

#[derive(Debug, Clone, PartialEq)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Rectangle {
    pub top_left: Point,
    pub width: f64,
    pub height: f64,
}
