// Code generated by sdp-gen. DO NOT EDIT.

#[derive(Debug, Clone, PartialEq)]
pub struct AllPrimitives {
    pub u8_field: u8,
    pub u16_field: u16,
    pub u32_field: u32,
    pub u64_field: u64,
    pub i8_field: i8,
    pub i16_field: i16,
    pub i32_field: i32,
    pub i64_field: i64,
    pub f32_field: f32,
    pub f64_field: f64,
    pub bool_field: bool,
    pub str_field: String,
}
