// Generated by sdp-gen - DO NOT EDIT

public struct Point {
    public var x: Float
    public var y: Float
}

public struct Rectangle {
    public var topLeft: Point
    public var bottomRight: Point
    public var color: UInt32
}

public struct Scene {
    public var name: String
    public var mainRect: Rectangle
    public var count: UInt32
}
