/* encode.hpp - Encoding functions for complex
 * Generated by sdp-gen - DO NOT EDIT
 */

#ifndef COMPLEX_ENCODE_HPP
#define COMPLEX_ENCODE_HPP

#include "types.hpp"
#include <cstdint>
#include <cstddef>

namespace sdp {

/* Calculate encoded size of Parameter */
size_t parameter_size(const Parameter& msg);

/* Encode Parameter to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least parameter_size() bytes
 */
size_t parameter_encode(const Parameter& msg, uint8_t* buf);

/* Calculate encoded size of Plugin */
size_t plugin_size(const Plugin& msg);

/* Encode Plugin to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least plugin_size() bytes
 */
size_t plugin_encode(const Plugin& msg, uint8_t* buf);

/* Calculate encoded size of AudioDevice */
size_t audio_device_size(const AudioDevice& msg);

/* Encode AudioDevice to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least audio_device_size() bytes
 */
size_t audio_device_encode(const AudioDevice& msg, uint8_t* buf);

}  // namespace sdp

#endif  // COMPLEX_ENCODE_HPP
