/* encode.hpp - Encoding functions for audiounit_cpp
 * Generated by sdp-gen - DO NOT EDIT
 */

#ifndef AUDIOUNIT_CPP_ENCODE_HPP
#define AUDIOUNIT_CPP_ENCODE_HPP

#include "types.hpp"
#include <cstdint>
#include <cstddef>

namespace sdp {

/* Calculate encoded size of Parameter */
size_t parameter_size(const Parameter& msg);

/* Encode Parameter to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least parameter_size() bytes
 */
size_t parameter_encode(const Parameter& msg, uint8_t* buf);

/* Calculate encoded size of Plugin */
size_t plugin_size(const Plugin& msg);

/* Encode Plugin to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least plugin_size() bytes
 */
size_t plugin_encode(const Plugin& msg, uint8_t* buf);

/* Calculate encoded size of PluginRegistry */
size_t plugin_registry_size(const PluginRegistry& msg);

/* Encode PluginRegistry to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least plugin_registry_size() bytes
 */
size_t plugin_registry_encode(const PluginRegistry& msg, uint8_t* buf);

}  // namespace sdp

#endif  // AUDIOUNIT_CPP_ENCODE_HPP
