// Generated by sdp-gen - DO NOT EDIT

public struct ArraysOfPrimitives {
    public var u8Array: ContiguousArray<UInt8>
    public var u32Array: ContiguousArray<UInt32>
    public var f64Array: ContiguousArray<Double>
    public var strArray: ContiguousArray<String>
    public var boolArray: ContiguousArray<Bool>

    public init(u8Array: ContiguousArray<UInt8>, u32Array: ContiguousArray<UInt32>, f64Array: ContiguousArray<Double>, strArray: ContiguousArray<String>, boolArray: ContiguousArray<Bool>) {
        self.u8Array = u8Array
        self.u32Array = u32Array
        self.f64Array = f64Array
        self.strArray = strArray
        self.boolArray = boolArray
    }
}

public struct Item {
    public var id: UInt32
    public var name: String

    public init(id: UInt32, name: String) {
        self.id = id
        self.name = name
    }
}

public struct ArraysOfStructs {
    public var items: ContiguousArray<Item>
    public var count: UInt32

    public init(items: ContiguousArray<Item>, count: UInt32) {
        self.items = items
        self.count = count
    }
}
