// Generated by sdp-gen - DO NOT EDIT

public struct ArraysOfPrimitives {
    public var u8Array: [UInt8]
    public var u32Array: [UInt32]
    public var f64Array: [Double]
    public var strArray: [String]
    public var boolArray: [Bool]
}

public struct Item {
    public var id: UInt32
    public var name: String
}

public struct ArraysOfStructs {
    public var items: [Item]
    public var count: UInt32
}
