// Generated by sdp-gen - DO NOT EDIT

/// Request Basic struct with optional metadata (RC Feature 1 test)
public struct Request {
    /// id Request ID (always present)
    public var id: UInt32
    /// metadata Optional user metadata
    public var metadata: Metadata?
}

/// Metadata User metadata
public struct Metadata {
    /// userId User ID
    public var userId: UInt64
    /// username Username
    public var username: String
}

/// Config Complex example with nested optional fields
public struct Config {
    /// name Configuration name
    public var name: String
    /// database Optional database settings
    public var database: DatabaseConfig?
    /// cache Optional cache settings
    public var cache: CacheConfig?
}

/// DatabaseConfig Database configuration
public struct DatabaseConfig {
    /// host Database host
    public var host: String
    /// port Database port
    public var port: UInt16
}

/// CacheConfig Cache configuration
public struct CacheConfig {
    /// sizeMb Cache size in MB
    public var sizeMb: UInt32
    /// ttlSeconds Time to live in seconds
    public var ttlSeconds: UInt32
}

/// Document Example with optional array (wrapped struct containing array)
public struct Document {
    /// id Document ID
    public var id: UInt32
    /// tags Optional tags wrapper
    public var tags: TagList?
}

/// TagList Wrapper for tag array
public struct TagList {
    /// items Array of tags
    public var items: [String]
}
