// Code generated by sdp-gen. DO NOT EDIT.

#![allow(dead_code)]

#[derive(Debug, Clone, PartialEq)]
pub struct DeviceList {
    pub devices: Vec<Device>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Device {
    pub id: u32,
    pub name: String,
    pub parameters: Vec<Parameter>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Parameter {
    pub name: String,
    pub value: f64,
}

