// Generated by sdp-gen - DO NOT EDIT

public struct Parameter {
    public var id: UInt32
    public var name: String
    public var value: Float
    public var min: Float
    public var max: Float

    public init(id: UInt32, name: String, value: Float, min: Float, max: Float) {
        self.id = id
        self.name = name
        self.value = value
        self.min = min
        self.max = max
    }
}

public struct Plugin {
    public var id: UInt32
    public var name: String
    public var manufacturer: String
    public var version: UInt32
    public var enabled: Bool
    public var parameters: ContiguousArray<Parameter>

    public init(id: UInt32, name: String, manufacturer: String, version: UInt32, enabled: Bool, parameters: ContiguousArray<Parameter>) {
        self.id = id
        self.name = name
        self.manufacturer = manufacturer
        self.version = version
        self.enabled = enabled
        self.parameters = parameters
    }
}

public struct AudioDevice {
    public var deviceId: UInt32
    public var deviceName: String
    public var sampleRate: UInt32
    public var bufferSize: UInt32
    public var inputChannels: UInt16
    public var outputChannels: UInt16
    public var isDefault: Bool
    public var activePlugins: ContiguousArray<Plugin>

    public init(deviceId: UInt32, deviceName: String, sampleRate: UInt32, bufferSize: UInt32, inputChannels: UInt16, outputChannels: UInt16, isDefault: Bool, activePlugins: ContiguousArray<Plugin>) {
        self.deviceId = deviceId
        self.deviceName = deviceName
        self.sampleRate = sampleRate
        self.bufferSize = bufferSize
        self.inputChannels = inputChannels
        self.outputChannels = outputChannels
        self.isDefault = isDefault
        self.activePlugins = activePlugins
    }
}
