// Generated by sdp-gen - DO NOT EDIT

public struct Parameter {
    public var id: UInt32
    public var name: String
    public var value: Float
    public var min: Float
    public var max: Float
}

public struct Plugin {
    public var id: UInt32
    public var name: String
    public var manufacturer: String
    public var version: UInt32
    public var enabled: Bool
    public var parameters: [Parameter]
}

public struct AudioDevice {
    public var deviceId: UInt32
    public var deviceName: String
    public var sampleRate: UInt32
    public var bufferSize: UInt32
    public var inputChannels: UInt16
    public var outputChannels: UInt16
    public var isDefault: Bool
    public var activePlugins: [Plugin]
}
