// Code generated by sdp-gen. DO NOT EDIT.
// https://github.com/shaban/serial-data-protocol

//! Self-contained SDP generated package with embedded wire format runtime.
//! This crate has no dependencies on external SDP libraries.

mod wire;         // Embedded: Read/Write trait API
mod wire_slice;   // Embedded: Direct slice API (faster)
mod types;
mod encode;
mod decode;
mod message_encode;  // Message mode: Self-describing messages
mod message_decode;  // Message mode: Decoders + enum dispatcher

pub use types::*;
pub use encode::*;
pub use decode::*;
pub use message_encode::*;
pub use message_decode::*;

// Re-export common wire format types
pub use wire::{Error, Result, Encoder, Decoder};
pub use wire_slice::{SliceError, SliceResult};
