/* encode.hpp - Encoding functions for arrays_cpp
 * Generated by sdp-gen - DO NOT EDIT
 */

#ifndef ARRAYS_CPP_ENCODE_HPP
#define ARRAYS_CPP_ENCODE_HPP

#include "types.hpp"
#include <cstdint>
#include <cstddef>

namespace sdp {

/* Calculate encoded size of ArraysOfPrimitives */
size_t arrays_of_primitives_size(const ArraysOfPrimitives& msg);

/* Encode ArraysOfPrimitives to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least arrays_of_primitives_size() bytes
 */
size_t arrays_of_primitives_encode(const ArraysOfPrimitives& msg, uint8_t* buf);

/* Calculate encoded size of Item */
size_t item_size(const Item& msg);

/* Encode Item to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least item_size() bytes
 */
size_t item_encode(const Item& msg, uint8_t* buf);

/* Calculate encoded size of ArraysOfStructs */
size_t arrays_of_structs_size(const ArraysOfStructs& msg);

/* Encode ArraysOfStructs to buffer
 * Returns: Number of bytes written
 * Note: Buffer must be at least arrays_of_structs_size() bytes
 */
size_t arrays_of_structs_encode(const ArraysOfStructs& msg, uint8_t* buf);

}  // namespace sdp

#endif  // ARRAYS_CPP_ENCODE_HPP
