// Code generated by sdp-gen. DO NOT EDIT.

#[derive(Debug, Clone, PartialEq)]
pub struct Parameter {
    pub id: u32,
    pub name: String,
    pub value: f32,
    pub min: f32,
    pub max: f32,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Plugin {
    pub id: u32,
    pub name: String,
    pub manufacturer: String,
    pub version: u32,
    pub enabled: bool,
    pub parameters: Vec<Parameter>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct AudioDevice {
    pub device_id: u32,
    pub device_name: String,
    pub sample_rate: u32,
    pub buffer_size: u32,
    pub input_channels: u16,
    pub output_channels: u16,
    pub is_default: bool,
    pub active_plugins: Vec<Plugin>,
}
