/* decode.hpp - Decoding functions for audiounit_cpp
 * Generated by sdp-gen - DO NOT EDIT
 */

#ifndef AUDIOUNIT_CPP_DECODE_HPP
#define AUDIOUNIT_CPP_DECODE_HPP

#include "types.hpp"
#include <cstdint>
#include <cstddef>
#include <stdexcept>

namespace sdp {

/* Decode error exception */
class DecodeError : public std::runtime_error {
public:
    explicit DecodeError(const char* msg) : std::runtime_error(msg) {}
};

/* Decode Parameter from buffer
 * Throws DecodeError on failure
 */
Parameter parameter_decode(const uint8_t* buf, size_t buf_len);

/* Decode Plugin from buffer
 * Throws DecodeError on failure
 */
Plugin plugin_decode(const uint8_t* buf, size_t buf_len);

/* Decode PluginRegistry from buffer
 * Throws DecodeError on failure
 */
PluginRegistry plugin_registry_decode(const uint8_t* buf, size_t buf_len);

}  // namespace sdp

#endif  // AUDIOUNIT_CPP_DECODE_HPP
