/* decode.hpp - Decoding functions for arrays
 * Generated by sdp-gen - DO NOT EDIT
 */

#ifndef ARRAYS_DECODE_HPP
#define ARRAYS_DECODE_HPP

#include "types.hpp"
#include <cstdint>
#include <cstddef>
#include <stdexcept>

namespace sdp {

/* Decode error exception */
class DecodeError : public std::runtime_error {
public:
    explicit DecodeError(const char* msg) : std::runtime_error(msg) {}
};

/* Decode ArraysOfPrimitives from buffer
 * Throws DecodeError on failure
 */
ArraysOfPrimitives arrays_of_primitives_decode(const uint8_t* buf, size_t buf_len);

/* Decode Item from buffer
 * Throws DecodeError on failure
 */
Item item_decode(const uint8_t* buf, size_t buf_len);

/* Decode ArraysOfStructs from buffer
 * Throws DecodeError on failure
 */
ArraysOfStructs arrays_of_structs_decode(const uint8_t* buf, size_t buf_len);

}  // namespace sdp

#endif  // ARRAYS_DECODE_HPP
